### ISSUE TITLE
Saucelabs tags filter is not working

### ISSUE THREAD

**Issue by evilaliv3** [exogen/badge-matrix#10]
we are evaluating the adoption of badge-matrix for integration with the [https://github.com/globaleaks/GlobaLeaks](GlobaLeaks) project.

The feature we are looking forward is the possibility to get the saucelab badge for a specific branch.
For this reason i'm using tags like 'master', 'devel' that are the main branches.

While then retesting the following url i've seen that they are not working: https://badges.herokuapp.com/sauce/globaleaks?tag=devel

is this a know issue of the badge-matrix?

**Comment by exogen** [comment]
@evilaliv3 It appears just to be due to the newly introduced Sauce Labs rate limiting; badge-matrix is currently making unauthenticated requests but I'm working on fixing that now.

More of an issue might be why it's needing to make so many requests to generate your badge in the first place. Looking at the logs, it was trying to collect over 1000 jobs to determine your build status.

Making [one of the requests](https://saucelabs.com/rest/v1/globaleaks/jobs?full=true&skip=0&limit=500) manually shows that `build` is set to `null`. When you trigger jobs with Sauce Labs, be sure to set `build` to a different build number/ID for each build so that it can be determined which jobs are part of the the same build.

See this part of the docs:

> Sauce Labs’ API doesn’t allow filtering by build, so finding the jobs for a build can be a bit of a hassle:
> - If the requested build is not in the first 500 results returned by the API, then you should specify `from` and `to` to limit the query window to the time span of the build.
> - If no `from` is given, then stop fetching more jobs from the API when a different build number is encountered.
> 
> Jobs with a null value for build are never included.

**Comment by evilaliv3** [comment]
great! let me give it a try!

**Comment by exogen** [comment]
As of d1cd255 badge-matrix is now making authenticated requests, but I confirmed that it's still returning "unknown" due to the `build` issue. If you're using Travis to connect to Sauce Labs, there should be a special way to send Sauce Labs your Travis build number via environment variables. Hope that helps!

**Comment by evilaliv3** [comment]
So strange;

we set correctly `"browser_capabilities['build'] = process.env.TRAVIS_BUILD_NUMBER;"`

i will investigate thanks

**Comment by exogen** [comment]
@evilaliv3 I noticed Sauce Labs' own example of configuring Protractor looks like your config, but the Protractor reference config has this `sauceBuild` setting: https://github.com/angular/protractor/blob/7c124f33f0338097829e3491506864cbfaca4836/docs/referenceConf.js#L75-L76

Maybe just set it in both places, `sauceBuild` and `capabilities.build`, and see if it works?

**Comment by evilaliv3** [comment]
Thank you so much @exogen i confirm that the issue was that and you can see the great result of using badge-matrix in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/217034/18614299/0485a700-7d8c-11e6-9e7a-62be1c70cce9.png)

**Comment by exogen** [comment]
@evilaliv3: Great news, and thanks for the screenshot – I've added iPad and iPhone specific logos. :)
